name: Build Web App
 
on: workflow_dispatch
 
jobs:
  build:
 
    runs-on: windows-2019
 
    steps:

    - name: Get current date
      id: date
      run: |
        $date = Get-Date -Format "yyyyMMdd"
        $build_number = $env:GITHUB_RUN_NUMBER
        Write-Output $build_number
